# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=254700, help_text='Country Phone Number. E.g +254... ', max_length=13),
            preserve_default=False,
        ),
    ]
