# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Country Phone Number. E.g +254... ', max_length=13, unique=True),
        ),
    ]
